

ingress_addr = "[::1]:8080"

[[transports]]

[transports.transport]
transport_type = "tls_plain"

[transports.transport.args]
address = "192.168.100.3:4443"
host = "tls-test.domain.com"
id_pubkey = "gyKl6DN9hgdPGhEzdf9gY4Ha2GzrOwSzLCguxeTVTJU="