public_ips = ["192.168.100.3"]

[forward]
address = "[::1]:50001"

[[transports]]
transport_type = "quic_plain"

[transports.args]
stateless_retry = false
listen = "[::]:4433"

# Path to file containing PEM encoded ed25519 identity private key, for use in ED25519 based self signed certs
# private_ed25519_identity_key_file = '/etc/nym/default-nym-node/bridges/ed25519_identity'

identity_key = "fditK5JfNM/88mLWd3ccbLasSrHA5dw1wj+/+1bfGWk="


[[transports]]
transport_type = "tls_plain"

[transports.args]
listen = "[::]:4443"

# Path to file containing PEM encoded ed25519 identity private key, for use in ED25519 based self signed certs
# private_ed25519_identity_key_file = '/etc/nym/default-nym-node/bridges/ed25519_identity'

identity_key = "fditK5JfNM/88mLWd3ccbLasSrHA5dw1wj+/+1bfGWk="
