[forward]
address = "[::1]:50001"

[[transports]]
transport_type = "quic_plain"

[transports.args]
stateless_retry = false
listen = "[::1]:4443"
identity_key = "fditK5JfNM/88mLWd3ccbLasSrHA5dw1wj+/+1bfGWk="




[[transports]]
transport_type = "tls_plain"

[transports.args]
listen = "[::1]:4443"
identity_key = "fditK5JfNM/88mLWd3ccbLasSrHA5dw1wj+/+1bfGWk="