
name: ci-build-upload-binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "14 0 * * *"

jobs:
  publish-nym:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_PERMIT_COPY_RENAME: 1
    steps:
      - uses: actions/checkout@v4

      - name: Prepare build output directory
        shell: bash
        env:
          OUTPUT_DIR: ci-builds/${{ github.ref_name }}
        run: |
          rm -rf ci-builds || true
          mkdir -p $OUTPUT_DIR
          echo $OUTPUT_DIR
      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install lintian

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build all binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release ${{ env.CARGO_FEATURES }}

      - name: Install cargo-deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb

      - name: Build deb Package
        uses: actions-rs/cargo@v1
        with:
          command: deb

      - name: Lint deb packages
        shell: bash
        run: lintian target/debian/nym-bridge*.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nym-bridge-artifacts
          path: |
            target/release/nym-bridge
            target/release/nym-cfg
            target/debian/nym-bridge*.deb
          retention-days: 30
